### ISSUE TITLE
SSHD not starting on CentOS 8 VM?

### ISSUE THREAD

**Issue by konstantinblaesi** [gsauthof/dracut-sshd#12]
##### Description
I am booting a CentOS 8 via KVM / virt-manager with kernel options `rd.neednet=1 ip=dhcp`
##### Expected behavior
I can login via ssh to enter the password
##### Observed behavior
Connection on port 22 is refused
( implying that the network setup via dhcp works fine right? )
##### Additioal Information
If I add `rd.break` to the cmdline, enter the LUKS password using virt-manager I get dropped to the dracut rescue shell and I can connect via ssh. This is still the initramfs sshd right?

Do you have some tips how to debug this?

**Comment by konstantinblaesi** [comment]
Is this some entropy issue? If I just start typing at the local LUKS password prompt, the sshd server is availble shortly after. If I don't do anything even after 1m30s there's still no sshd server availble.
I am checking port 22 of my VM using `while [ true ] ; do sudo nmap -sS -p 22 192.168.122.178 | grep "22/tcp"; done`

**Comment by konstantinblaesi** [comment]
Problem seems to be entropy related!
`cat /proc/sys/kernel/random/entropy_avail` prints
* Host: 3795
* Guest: 424 (after dropping emergency shell via `rd.break`)

After adding the RNG to the VM the sshd came up pretty instant :)

![random](https://user-images.githubusercontent.com/5871169/65834123-24386600-e2d8-11e9-8beb-d7b7179d53be.png)

**Comment by gsauthof** [comment]
Yeah, not having enough entropy is a common thing when testing such stuff in a VM.

This is also the reason why the qemu call in the test-suite [has `-device virtio-rng-pci` set][1].

Depending on the host even the entropy of the host system might run out.

If this happens in a test environment I start `haveged` (on the VM host, not inside the VM).

---

**2026 update**: With Linux 5.6 or later the kernel cannot run out of entropy like this, anymore.
Thus, there isn't a need anymore to run something like haveged on the host system.

A few years ago, the old dracut-sshd test suite was replaced and the new one uses virsh for the VM management which adds a `virtio-rng-pci` device to the guest, by default.

[1]: https://github.com/gsauthof/dracut-sshd/blob/3384925f17523ac4ed11d3dccfd8f08f73c9114c/ci/run_vm.py#L70
