### ISSUE TITLE
sshd service first start fails

### ISSUE THREAD

**Issue by Kaari** [gsauthof/dracut-sshd#13]
Hello,

I have an issue on my centos 8 VM (I'm not using networkd - it is not available in centos 8).

During the sysinit, sshd fails to start the first time, it works afterwards, I have no relevant logs from journald (only process exited with code 1), therefore the boot process is delayed for a minute until sshd tries to restart.

Maybe you know of this issue, if not, please could you tell me how I could get more relevant logs about why sshd fails to start ? I tried adding `-d` to the `Exec` without much success.

Thank you very much

**Comment by gsauthof** [comment]
Please clarify, which sshd are you referring to? The early-boot sshd or the system sshd  (i.e. after the switch-root happened)?

**Comment by Kaari** [comment]
Thx for the reply,
I'm talking about the sshd which is shipped in the initramfs, during the early boot process.

**Comment by gsauthof** [comment]
Have you checked if this is caused by a lack of entropy?

cf. issue #12

**Comment by Kaari** [comment]
Woah, magically it works now!
So I created an unnecessary issue:upside_down_face:
I had no idea this kind of situation could arise, I learned something today, thanks!
