### ISSUE TITLE
RFC: do not include all of /etc/systemd/network/* when using systemd-networkd

### ISSUE THREAD

**Issue by LaserEyess** [gsauthof/dracut-sshd#23]
This may seem like a configuration difference but there are very real reasons not to include these files:

1. Some devices (tun, tap, wireguard) can have private information included in the configurations. Leaking this information in the initramfs may not be ideal at best, and a security issue at worst.
2. Identical network configurations during boot and a running system are not always desired or even practical/possible.

I believe the above reasons are why not even dracut's built-in systemd-networkd brings over the configurations to the initramfs. Instead they give the option of using `install_items=`/`install_optional_items=` to include what you need. Another alternative would be to glob something like `99-dracut-*.{network,netdev,link}` so the user can explicitly say they want those files in their initramfs.

Willing to make a PR for this if you think it's a good idea.

**Comment by gsauthof** [comment]
These are valid points.

Using `install_items=` is probably the best way.

I would do it like this:

1. remove the code form `module-setup.sh`
2. update the README, e.g. suggest something like `echo 'install_items+="/etc/systemd/network/20-wired.network"' > /etc/drcaut.conf.d/20-networkd.conf` for a simple seutp
3. update the setup in the test-suite
