### ISSUE TITLE
RFC: Use Include directive in sshd_config instead of env variables

### ISSUE THREAD

**Issue by LaserEyess** [gsauthof/dracut-sshd#24]
I think something like 
```
SyslogFacility                  AUTHPRIV
PermitRootLogin                 prohibit-password
AuthorizedKeysFile              .ssh/authorized_keys
AuthenticationMethods           publickey
UsePAM                          no
X11Forwarding                   no

AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE

Include /etc/ssh/dracut_sshd_config
```
Would be a nice addition since it allows you to use an sshd_config format to configure dracut's sshd explicitly. Putting `$SSHD_OPTS` in `/etc/sysconfig/sshd` seems like a compromise of allowing dracut specific options without pulling in your system's `/etc/sshd_config`. 

Willing to make a PR for this as well.

**Comment by gsauthof** [comment]
Would that even work?

I see `Include` documented in [ssh_config(5)](https://manpath.be/f31/openssh-clients/8.1p1-1.fc31.x86_64/5/ssh_config#L629) but not in [sshd_config(5)](https://manpath.be/f31/5/sshd_config).

**Comment by LaserEyess** [comment]
It seems to exist here man7.org/linux/man-pages/man5/sshd_config.5.html

Arch's sshd_config(5) has it.

**Comment by gsauthof** [comment]
Ok, I close it then for now.
