### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by lordskh** [gsauthof/dracut-sshd#30]
Hi, when I attempt to ssh to unlock my system, I get `Permission denied (publickey)`

But once the system in booted I am able to ssh in with the same key. I was concerned that maybe my `authorized_keys` file wasn't getting loaded properly but 
```
# lsinitrd | grep authorized_keys                                        
-rw-------   1 root     root          554 Mar 16 11:15 root/.ssh/authorized_keys
```
would lead me to believe that that's not the problem.

**Comment by gsauthof** [comment]
Try to debug this issue by looking at the ssh log messages from early boot (e.g. with `journalctl -b`) and/or unpack the generated initramfs archive and inspect the included `authorized_keys` to check whether it matches your expectations/what you have under `/root/.ssh`. Also check the permissions of the `/root` and `/root/.ssh` directories in the initramfs archive.

**Comment by lordskh** [comment]
The correct key is in my initramfs archive. 
The permissions in the archive for `/root` are:
```
drwxr-xr-x.  3 root    root        4096 May 28 09:07 root
```
And for `/root/.ssh`:
```
drwx------.  2 root    root    4096 May 28 09:07 .ssh
```
Which seem fine.

**Comment by gsauthof** [comment]
Is the sshd logging any errors during early-boot?

**Comment by lordskh** [comment]
Not beyond the warning about `UsePAM no`

**Comment by gsauthof** [comment]
You can also compare the `ssh -v` output when you get the `Permission denied (publickey)` error vs.  when the login works. Perhaps you see some difference in what keys are offered or something like that.

**Comment by saibotk** [comment]
Actually I am currently experiencing the exact same problem. 
I am testing this on a fresh Fedora 32 Server installation, if this might help.

**Comment by saibotk** [comment]
Okay so at least on fedora 32, when you did not create a root user password (just your own user and made him member of the wheel group), you cannot login via ssh, as the user account is locked. See https://unix.stackexchange.com/questions/193066/how-to-unlock-account-for-public-key-ssh-authorization-but-not-for-password-aut

**Comment by gsauthof** [comment]
@saibotk this sounds similar to issue #19 - can you confirm?

I'll add something to the README.

**Comment by saibotk** [comment]
Thank you :+1:

**Comment by lum4chi** [comment]
Sorry for necroposting, but I had this exact problem but wasn't caused by locked root user with `!`. Instead problem was that `sshd-session[1282]: User root not allowed because shell /bin/bash does not exist` but just changing the default shell with `sudo usermod -s /bin/sh root` was not enough and also needed to explicitly add `install_items+=" /etc/passwd "`. 

I'm on ubuntu server 26.04.

Hope it helps.

**Comment by mm-tarr** [comment]
Also in the ubuntu server 26.04: By adding the bash as module in dracut `add_dracutmodules+=" crypt network sshd bash` works as well, instead of changing the default shell.

Let me know if there is any downside to that approach.

**Comment by gsauthof** [comment]
> Let me know if there is any downside to that approach.

The only downside of adding bash is the size increase, i.e. 1.4 MiB (uncompressed) or so.

But given the median RAM size of a few gigabytes on anything that can run current Linux kernels, this isn't something one would loose sleep over.

For example, Fedora symlinks /bin/sh to bash anyways and simply includes bash in the initramfs, by default.

Related pull request: #121
