### ISSUE TITLE
Reboot in Dracut

### ISSUE THREAD

**Issue by rvalle** [gsauthof/dracut-sshd#31]
Hi!

Is it possible to trigger a reboot from the ssh session?

Something went wrong inserting the password and the server did not boot. systemd-tty-...password will not ask for password anymore.

I know is an edge case, but looks like I might beed to make a physical reset otherwise.

I tried reboot, but just waits.

**Comment by gsauthof** [comment]
Something like this should work over ssh and immediately reboot the machine:

```
echo 1 > /proc/sys/kernel/sysrq
echo b > /proc/sysrq-trigger
```

That said, under usual circumstances `systemd-tty-ask-password-agent` should still work even if one enters a wrong passwords multiple times.

See also the Timeout Section in the dracut-sshd README.

**Comment by rvalle** [comment]
You are right, eventually the problem fixed by itself. Perhaps due to timeout.
I was fiddling with Systemd and the password agents. At some point it did not ask for more passwords, would not boot, and would not reboot either.

But looks like a timeout killed the session and the next ssh connection was asked for passwords normally.
