### ISSUE TITLE
non-interactive device unlock/ansible

### ISSUE THREAD

**Issue by rvalle** [gsauthof/dracut-sshd#32]
Is it possible to unlock the device in an non-interactive way?

I am trying to execute a raw command from ansible but I cannot find out which command to provide. 

Any ideas how can I unlock the device in this case?

**Comment by gsauthof** [comment]
You need something that drives a pseudo-tty - e.g. pexpect:

```
h=example.org
f=pw
python -c 'import pexpect.pxssh
s = pexpect.pxssh.pxssh()
s.login("'$a'", "root")
s.sendline("systemd-tty-ask-password-agent")
s.sendline(open("'$f'").read().strip())
s.prompt()
s.expect(pexpect.EOF)
s.close()'
```

You can integrate this with Ansible by e.g. delegating this snippet to localhost.

**Comment by rvalle** [comment]
@gsauthof that suggestion could evolve into a raw_expect module for ansible. I think the expect module they have should be raw anyway, meaning no python is expected on the target host.

I was trying another strategy. It is possible to unlock using cryptsetup luksOpen command but then Systemd doesn't realise this took place.

I tried them to restart some of the services or targets and almost got it to continue booting... 

Another issue is that you need to know the devices and target to pass to cryptsetup unless there's a way to get the kernel parameters.

**Comment by pschmitt** [comment]
FIY the following works just fine:

```bash
echo 'THE_SECRET_LUKS_PASSWORD' | ssh -t root@fnuc systemd-tty-ask-password-agent
```

**Comment by rvalle** [comment]
@pschmitt thanks! yes, it does work.

Trying now to execute it in a raw ansible module, not managing.

I don't understand why if I just ssh first to the server and then do:

```
echo 'THE_SECRET_LUKS_PASSWORD' |  systemd-tty-ask-password-agent
```

then asks for the prompt

**Comment by gsauthof** [comment]
I'm closing this issue because some possible solutions were pointed out.

**Comment by gsauthof** [comment]
> FIY the following works just fine:
> 
> ```shell
> echo 'THE_SECRET_LUKS_PASSWORD' | ssh -t root@example.com systemd-tty-ask-password-agent
> ```

Even this works for me:

```
< password_plain_file ssh root@example.org systemd-tty-ask-password-agent
```

Perhaps `systemd-tty-ask-password-agent` checks if it's connected to a tty - and if not it falls back to a simple read from stdin. And then it looks like its tty detection logic only succeeds for interactive logins and not for `ssh -t`. Which is indeed a bit surprising.

TBH, all this is a bit surprising as most other password prompting tools are known to only work over a tty/pty.

Thus, in the past, I didn't even bother to test this and directly used `pexpect` for non-interactive unlocking.

**Comment by gsauthof** [comment]
Regarding Ansible integration, I've created some playbooks which also need to non-interactively unlock a LUKS encrypted root filesystem. For example, the unlock task itself:

https://github.com/gsauthof/playbook/blob/master/fedora/initramfs/ansible/unlock_tasks.yml

I didn't use the raw module because it [doesn't support `stdin`, yet](https://github.com/ansible/ansible/issues/34556).

Other Ansible pitfalls are:

- not waiting long enough for switch-root has happened after the unlock such that Ansible gets confused about missing commands/a missing temporary directory later on
- using `become: yes` - this doesn't work in early userspace because there is no sudo. Ansible then runs into a timeout but doesn't complain about the missing sudo in its error message

**Comment by pschmitt** [comment]
> not waiting long enough for switch-root has happened after the unlock such that Ansible gets confused about missing commands/a missing temporary directory later on

You may be able to get around this issue by awaiting another service. In my setup I wait for cockpit to be up on port 9090 for instance. This obviously requires a TCP service to be auto-started on the target host. You could also try to log in as a non-root user and check how sshd responds, if it is something along the lines of "regular users are not allowed to log in yet" then wait some more etc.
