### ISSUE TITLE
Centos 8  port 22: Connection refused

### ISSUE THREAD

**Issue by LecrisUT** [gsauthof/dracut-sshd#33]
I've been trying to get this to work on my Centos installation in order to unlock the encrypted hard-drive. It seems that the network and SSH service is enabled on startup, but for some reason the connection is refused. It might be a firewall issue, but I don't know how to check that.

Some other system information for easier search: Ethernet port is `enp2s0`, the ethernet driver is manually installed.

Here is the message log of the boot up:
https://gist.github.com/LecrisUT/6c9f75467ffce10ced7735b4ef8ad3d0

**Comment by gsauthof** [comment]
The early boot environment usually doesn't include a firewall. In your boot log it looks like the root filesystem is automatically mounted before the `Switching root` line. Thus, it doesn't look like your root filesystem is encrypted.

(Everything before the `Switching root` line happens in the early boot environment where the root filesystem is mounted and where dracut-sshd runs.)

Are you sure that you have full root fs encryption?

If you don't have it then you don't need dracut-sshd.

To diagnose ssh connectivity issues you can use `nmap` and `ssh -v`. And by looking at the host's ssh log by other means (e.g. from a console session, in case you have physical access while debugging this).

Posting the complete journal inline is a bit excessive and doesn't help with google. Au contraire, it adds much noise and thus generates too many hits for unrelated stuff. Thus, it's better to only quote significant snippets you've already identified (if possible) or upload it to Github Gists or some pastebin service and link it.

**Comment by LecrisUT** [comment]
I'll use gist nect time, thnx for the tip.

The root directory is not encrypted. I am unsure of how that would impact read performance so I've left it open for now. I'll consider adding encryption to it later, hope it's not too complicated to do so. If I do that the current dracut-sshd setup will still be applicable? 

The problem is that the boot process still asks for fs decryption, and I'm unable to ssh with or without dracut-sshd at that stage. Do you have other tips on how to disable the decryption prompt or boot up?

**Comment by gsauthof** [comment]
The purpose of dracut-sshd is to provide an ssh daemon during early boot to be able to remotely log into the early boot environment when it blocks. Early boot blocks when e.g. the encrypted root fs needs to be unlooked, when an emergency shell is requested/started etc.

Thus, yes, you can use dracut-sshd to unlock your encrypted root fs.

On the other hand, if nothing blocks the early boot process then the early sshd almost immediately is terminated again by the switch-root procedure. Thus, it doesn't help you with your current situation.

Regarding the cryptsetup prompts you get in late boot: they might block remote-login, I'm not sure. Whether they should block remote login is debatable, you could argue that normal user login requires `/home` thus it makes sense if `/home` is encrypted. OTOH, remote root login should still be possible.

You can look into `/etc/crypttab` and `/etc/fstab` to influence what luks devices are prompted for during late boot and change the config such that your sshd is blocked anymore by those prompts. Start e.g. with [this paragraph][1]. The [UNIX Stackexchange site][2] is well suited for follow up questions.

Regarding performance: you can get an idea of the overhead by running `cryptsetup benchmark` on your hardware.


[1]: https://manpath.be/f32/systemd/245.4-1.fc32.x86_64/5/crypttab#L114
[2]: https://unix.stackexchange.com/

**Comment by LecrisUT** [comment]
Happy to report that your advice was spot on. Thank you for all the help
