### ISSUE TITLE
SSHD failed to start when ssh host key does not exist

### ISSUE THREAD

**Issue by sysnull789** [gsauthof/dracut-sshd#35]
Issue:
sshd service failed to start if it can't find any ssh host key.

![image](https://user-images.githubusercontent.com/69116838/89127851-4bac2080-d4f1-11ea-833d-e64c54e3a1cd.png)

Context:
When installing dracut-sshd inside kickstart %post section, ssh host key is not already generated at this stage (generated at first boot). 
The dracut install script (module-setup.sh) does not check if host key exist and build an initramfs image without it, resulting in shhd to not start.

Workarroud (in my case):
Pre-generate ssh host key with `ssh-keygen -A` before executing `dracut -v -f `

Enhancement:
Add a check inside module-setup.sh to ensure at least one ssh host key exist. 
if not drop an error when regenerating initramfs via dracut.

This would do the job:
```bash
    install() {
    local key_prefix key_type ssh_host_key authorized_keys totalhostkey hostkeyerror  
    hostkeyerror=0
    totalhostkey=0
    key_prefix=
    if [ "$(find /etc/ssh -maxdepth 1 -name 'dracut_ssh_host_*_key')" ]; then
        key_prefix=dracut_
    fi
    for key_type in dsa ecdsa ed25519 rsa; do
        ssh_host_key=/etc/ssh/"$key_prefix"ssh_host_"$key_type"_key
        ((totalhostkey++))
        if [ -f "$ssh_host_key" ]; then
            inst_simple "$ssh_host_key".pub /etc/ssh/ssh_host_"$key_type"_key.pub
            /usr/bin/install -m 600 "$ssh_host_key" \
                    "$initdir/etc/ssh/ssh_host_${key_type}_key"
        else
            ((hostkeyerror++))
        fi
    done

    if [ "${hostkeyerror}" -eq "${totalhostkey}" ]; then
       dfatal "No ssh_host_*_key or dracut_ssh_host_*_key found in /etc/ssh directory !"
       return 1
    fi
```

**Comment by gsauthof** [comment]
An extra check makes sense, I've prepared something and will push it soon.
