### ISSUE TITLE
SSH functionality, log into a LUKS encrypted CentOS 8 is not longer available after the package update

### ISSUE THREAD

**Issue by SDuesterhaupt** [gsauthof/dracut-sshd#39]
Currently, no SSH connection can be established to start an encrypted CentOS. Since an update of the dracut-sshd package, the following hook doesn't seem to work with a ```sudo dracut -f```:

Expected behaviour/output:
```
# Created symlink /var/tmp/dracut.6lfHIS/initramfs/etc/systemd/system/sysinit.target.wants/sshd.service -> /usr/lib/systemd/system/sshd.service.
```

Since the dracut-sshd update I miss this information.

I played with different cases within a virtual machine and a fresh installed and updated CentOS.

```
$ uname -a
Linux VM-X-XXXX 4.18.0-193.28.1.el8_2.x86_64 #1 SMP Thu Oct 22 00:20:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Finally I could find out:

It runs with dracut-sshd version 0.5.1-2 (and doesn't run with 0.6.2-1):

```
$ yum list dracut-sshd
...
Installierte Pakete
dracut-sshd.noarch     0.5.1-2.el8     @copr:copr.fedorainfracloud.org:gsauthof:dracut-sshd
Verfügbare Pakete
dracut-sshd.noarch     0.6.2-1.el8     copr:copr.fedorainfracloud.org:gsauthof:dracut-sshd 
dracut-sshd.src        0.6.2-1.el8     copr:copr.fedorainfracloud.org:gsauthof:dracut-sshd
```

**Comment by gsauthof** [comment]
The `Created symlink ...` diagnostics is gone because the quiet flag was added to that systemctl call:

```
diff --git a/46sshd/module-setup.sh b/46sshd/module-setup.sh
index 14cff63..c9caca6 100755
--- a/46sshd/module-setup.sh
+++ b/46sshd/module-setup.sh
-    systemctl --root "$initdir" enable sshd
+    systemctl -q --root "$initdir" enable sshd
```

That means the absence of this message may be a red herring.

You can check that by temporarily removing the `-q` flag again on your test system.

**Comment by gsauthof** [comment]
What kind of network setup do you use in the early boot environment? Networkd?

**Comment by SDuesterhaupt** [comment]
I use the possibility with the Dracut command line parameters and I checked again with the focus on the network environment.

Before that I read your instructions again. So I have checked the existance of the network modules inside the initramfs and the expected behaviour is:

```
sudo lsinitrd | grep 'network'
network-legacy
network
kernel-network-modules
```

In version 0.5.1-2 I needn't to create:

```
# cat /etc/dracut.conf.d/90-network.conf
add_dracutmodules+=" network "
```

In version 0.5.1-2 it's obligatory. Otherwise the dracut network module is missed.

I don't know really the reason but the situation itself is solved.

So the issue is solved.


Thank you for your dracut-sshd solution. :)

**Comment by gsauthof** [comment]
Good.

Regarding automatic dracut module dependencies: Older dracut-sshd versions implemented a heuristic to emit a dependency on a network dracut module.

After reflecting on some related challenges I realizes that there is just too much variance with respect to peoples network setups and distributions dracut-sshd runs on. For example, networkd vs. network-manager vs. some other method; early-boot setup vs. late-boot network requirements; etc.

I thus decided to remove this implicit network module dependency logic such that the network configuration is more explicit now.
