### ISSUE TITLE
Getting permission denied errors for systemd-networkd on boot

### ISSUE THREAD

**Issue by XenGi** [gsauthof/dracut-sshd#40]
Ahoi,
pretty happy to find this dracut module. Sadly I can't get it to work.
I've already jumped through a few hoops with systemd-networkd but that seems to work now.

```
$ networkctl
IDX LINK   TYPE     OPERATIONAL SETUP
  1 lo     loopback carrier     unmanaged
  2 enp2s0 ether    routable    configured
  3 enp3s0 ether    no-carrier  configuring
```
```
$ cat /etc/systemd/network/20-enp2s0.network
[Match]
Name=enp2s0
MACAddress=ff:00:bb:aa:rr:01

[Network]
DHCP=true
MulticastDNS=resolve
DNSSEC=allow-downgrade
$ cat /etc/systemd/network/20-enp3s0.network
[Match]
Name=enp3s0
MACAddress=ff:00:bb:aa:rr:02

[Network]
DHCP=true
MulticastDNS=resolve
DNSSEC=allow-downgrade
```
```
$ dns info dsracut-sshd
Installed Packages
Name      : dracut-sshd
Version   : 0.6.2
Release   : 1.el8
From repo : copr:copr.fedorainfracloud.org:gsauthof:dracut-sshd
```
```
$ cat /etc/centos-release
CentOS Linux release 8.2.2004 (Core)
```
```
$ cat /etc/dracut.conf.d/90-networkd.conf
install_items+=" /etc/systemd/network/20-enp2s0.network /etc/systemd/network/20-enp3s0.network "
add_dracutmodules+=" systemd-networkd "
```

When I reboot the system I get the following error before the password prompt:
```
[FAILED] Failed to start Network Service.
```
After booting journalctl has the following entries:
```
systemd[574]: systemd-networkd.service: Failed to execute command: Permission denied
systemd[574]: systemd-networkd.service: Failed at step EXEC spawning /usr/lib/systemd/systemd-networkd: Permission denied
```
I'm not sure what the issue is. I got a similar problem earlier when I had no read rights to my *.network files but I fixed that and regenerated the initrd.

**Comment by danimo** [comment]
Can you confirm that /usr/lib/systemd/systemd-networkd has the execute bit set (check with `lsinitrd`)?

**Comment by XenGi** [comment]
All set to 0755. Seems to be ok

**Comment by XenGi** [comment]
loaded dracut modules also seem ok:
- systemd
- systemd-initrd
- systemd-networkd
- networ-legacy
- network
- ifcfg
- sshd
- dracut-systemd

there are more but I guess these are the important ones.

**Comment by gsauthof** [comment]
Locking at

```
systemd[574]: systemd-networkd.service: Failed at step EXEC spawning /usr/lib/systemd/systemd-networkd: Permission denied
```

two things come to my mind:

1) This might even be caused by an ancestral directory having the wrong permissions - e.g. if `/usr/lib/systemd` would miss the execute bit. Perhaps worth checking the permissions of the complete path - in case you haven't already done that.
2) Might this be caused by an SELinux issue? You could check that by booting with `encorcing=0` added to the kernel command line, temporarily.

**Comment by XenGi** [comment]
`enforcing=0` didn't help.
The whole path has execute bits set for ugo.

**Comment by XenGi** [comment]
I suspect something in the service file. It is very restricted. Maybe something in there just doesn't work in the init but is fine in the running system.

**Comment by gsauthof** [comment]
> I suspect something in the service file. It is very restricted. Maybe something in there just doesn't work in the init but is fine in the running system.

Yeah, this may very well be.

The thing with RHEL 8 is that it doesn't support networkd. Recently, it's available via EPEL, IIRC.

I presume, the situation on CentOS 8 is basically the same.

Thus, perhaps the best way is to use and configure the Redhat supported network connectivity for early-boot (cf. https://github.com/gsauthof/dracut-sshd#network) - instead of networkd.

FWIW, in my last RHEL 8 tests with dracut-sshd I didn't use networkd, as well.

**Comment by XenGi** [comment]
I switched from `systemd-networkd` to the `network` module and that works. It would be nice to get systemd-networkd to work but thats fine for me now. Thx for the tip!

**Comment by gsauthof** [comment]
Yeah, it would be nice.

You could open a bug in the Red Hat Bugzilla against the EPEL networkd package (i.e. choose Product -> Fedora EPEL).

For reference:

- [rhel-8 bug regarding missing network -> closed as WONTFIX](https://bugzilla.redhat.com/show_bug.cgi?id=1650342)
- [comment that announces the EPEL package](https://bugzilla.redhat.com/show_bug.cgi?id=1650342#c38)
- [EPEL package review](https://bugzilla.redhat.com/show_bug.cgi?id=1789146)
