### ISSUE TITLE
No SSH host keys on fresh install

### ISSUE THREAD

**Issue by rosieeyes** [gsauthof/dracut-sshd#46]
Hiya, I've just been through a fresh Arch install on a remote host, and noticed that the SSH host keys won't be generated until after `sshd.service` - and thus, `sshdgenkeys.service` - is run for the first time. systemd won't run inside the typical arch-chroot part of the install process, which is all you have until you unlock the drives and boot Linux for the first time (not possible without the host keys).

Given that `sshdgenkeys.service` is basically just a thin wrapper around `ssh-keygen -A`, could we just create the missing host keys with `ssh-keygen -A` instead of [erroring out](https://github.com/gsauthof/dracut-sshd/blob/master/46sshd/module-setup.sh#L36)? Or perhaps just a text fix to essentially say "run ssh-keygen -A"?

It's not a huge issue, just a QoL change that I think would be nice. :)

**Comment by gsauthof** [comment]
Hm, I don't know much about Arch. I don't even know if dracut-sshd is packaged for arch.

I don't think that the dracut-sshd module file is the right place to generate missing host keys. It feels like it would be a too surprising side-effect. I mean I can imagine people don't expecting it, accidentally copying such a chroot (with generated host keys) to a bunch of VMs without noticing for a long time that all of them ended up with the same host keys! Which would be a major security incident.

So I think that the generation of host keys should be done as part of a system provisioning procedure, before dracut is ran.

**Comment by rosieeyes** [comment]
That's a fair evaluation w.r.t. host key generation, you're right; I hadn't considered that. I definitely want to document the original issue I had somewhere/somehow, but I think putting it in code as I originally suggested would be an overstep (I forget how different things can be between distros).

I think we can close this, thank you. :)

P.S. If you're curious, dracut-sshd is 'available' as a PKGBUILD - build/install instructions, essentially - on the [Arch AUR](https://aur.archlinux.org/packages/dracut-sshd-git/), which is where I pulled it from.
