### ISSUE TITLE
Fedora 30 build

### ISSUE THREAD

**Issue by champtar** [gsauthof/dracut-sshd#5]
Hi @gsauthof,

could you enable Fedora 30 build on Copr?
Fedora 29 package works fine on Fedora 30, so I would say just tick a box and maybe do a new tag without changes should be enough

Thanks
Etienne

**Comment by gsauthof** [comment]
Thanks for the report. I've just enabled Fedora 30 (and Rawhide) in Copr and triggered a rebuild.

The Fedora 30 package should now be available for that Copr repository.
