### ISSUE TITLE
Ubuntu 20.04 - ssh Connection timed out - not working

### ISSUE THREAD

**Issue by GreedyBastard** [gsauthof/dracut-sshd#51]
Hello,

After going through all the steps, I can't connect to unlock the luks after reboot.

SERVER
Please enter passphrase for disk XXX (sda6_crypt):

CLIENT
ssh  -vv   root@192.168.10.77
OpenSSH_6.8p1-hpn14v6, OpenSSL 1.0.2h-fips  3 May 2016
debug1: Reading configuration data /root/.ssh/config
debug2: ssh_connect: needpriv 0
debug1: Connecting to 192.168.10.77 [192.168.10.77] port 22.
debug1: connect to address 192.168.10.77 port 22: Connection timed out
ssh: connect to host 192.168.10.77 port 22: Connection timed out

All steps :
Ubuntu Desktp 20.04 clean install.

SERVER
apt remove libreoffice*
apt update
apt upgrade
apt install -y qt5-default libqt5designer5 libqt5help5 python3-psutil \
 python3-pyqt5 python3-pyqt5.qtsvg python3-sip qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools \
 apt-file base-files btrfs-progs cbm cryptsetup cryptsetup-initramfs gcc \
 git libblkid-dev libc6 libc6-amd64-x32-cross libc6-dev libc6-dev-i386 \
 mc make ufw rsync lvm2 \
 dracut dracut-network

apt clean
apt autoremove

SERVER SSH config:

vi /etc/ssh/sshd_config
PermitRootLogin yes

#as root
passwd
#change root pwd to my_new_pwd

mkdir /root/.ssh

CLIENT:
#login as root
cd ~/.ssh/
ls -la *.pub
scp ~/.ssh/*.pub root@SERVER:/root/.ssh/
#end

SERVER:
#as root
cd /root/.ssh
cat *.pub >>authorized_keys
rm -f *.pub
cat authorized_keys

SERVER:
cd /opt
git clone https://github.com/gsauthof/dracut-ssh
cd dracut-ssh
cp -ri 46sshd /usr/lib/dracut/modules.d

vi /etc/systemd/network/20-wired.network
[Match]
Name=enp4s0

[Network]
DHCP=ipv4

vi /etc/dracut.conf.d/90-networkd.conf
install_items+=" /etc/systemd/network/20-wired.network "
add_dracutmodules+=" systemd-networkd "

vi /etc/default/grub
#modify:
GRUB_CMDLINE_LINUX_DEFAULT="quiet rd.neednet=1 ip=dhcp"

#then
update-grub

rm /root/dracut.log
dracut -f -v |tee -a /root/dracut.log

grep -i sshd /root/dracut.log
#sshd modue included -> OK!

reboot

What else can I do to get this up and running? 
Any help appreciated.

**Comment by gsauthof** [comment]
You can check #45 whether you are running into the same issue.

Also, if you have access to the console, you can add dracut specific parameter such that you are dropped into a dracut emergency shell where you can debug the situation a little bit. For example, by looking at the journal, checking the `systemctl status` of openssh etc.

Something like

```
rd.shell rd.break
```

should invoke the dracut shell.

**Comment by gsauthof** [comment]
I resolved #45 and documented some Ubuntu pitfalls in the README.
