### ISSUE TITLE
Decrypt Timeout on Arch

### ISSUE THREAD

**Issue by deimosian** [gsauthof/dracut-sshd#53]
Greetings, I have switched from grub to systemd-boot, mkinitcpio to dracut, and am using this for unlocking machines I am not sitting in front of. 

It works wonderfully _except_ that if I do not enter the password within ~90 seconds dracut launches the emergency shell. 

I see this was apparently an issue in the past on Fedora in the past and that's mentioned in the readme here, does anyone have any idea how to patch this on Arch?

**Comment by gsauthof** [comment]
You can look at the old Fedora bug reports for some hints/inspiration, e.g. start with:

https://bugzilla.redhat.com/show_bug.cgi?id=868421#c13

It might be related whether you include your `/etc/crypttab` in your initramfs archive or not. And what options it includes.

On my main system, I have a simple `/etc/crypttab` but it isn't included in the initramfs and I've explicitly added the  `rd.luks.uuid=...` parameter to the kernel parameters.

**Comment by gsauthof** [comment]
@deimosian  Could you resolve your issues?

**Comment by deimosian** [comment]
Not yet, no. I haven't had a chance to spend much time on it, but merely populating fstab and crypttab didn't do the trick.

**Comment by paulo-erichsen** [comment]
we should be able to close this ticket. I've tested on Arch today and it's working great and doesn't timeout

I'm also not using `/etc/crypttab` 

```
 5.19.3-arch1-1
```
