### ISSUE TITLE
CentOS 9

### ISSUE THREAD

**Issue by keachi** [gsauthof/dracut-sshd#56]
Hi there,
I love this project, it's great work!
Would it be possible to build it for CentOS Stream 9 too?

**Comment by gsauthof** [comment]
You mean for the Copr repository? I've just added CentOS Stream 9 there:

https://copr.fedorainfracloud.org/coprs/gsauthof/dracut-sshd/build/3029659/

But I haven't tested it on CentOS Stream 9, yet.

Hopefully, that environment doesn't require any changes to dracut-sshd.

**Comment by keachi** [comment]
Yes, I mean on copr. Thank you very much! I'll let you know when I test it.

**Comment by keachi** [comment]
I shortly tested it and it's working on CentOS Stream 9. Thank you very much!
