### ISSUE TITLE
COPR `epel-9-*`

### ISSUE THREAD

**Issue by atemp** [gsauthof/dracut-sshd#60]
Hi,

 is it possible to add a COPR repo for `epel-9-x86_64` and `epel-9-aarch64`?

Thanks!

**Comment by gsauthof** [comment]
Certainly.

FWIW, on copr, the `epel-9-*` targets are annotated with:

> Pre-release builds, against CentOS Stream 9 + EPEL 9, this will be changed once RHEL 9 is available. 

I also selected centos-stream-9-aarch64. (centos-stream-9-aarchx86_64 already was selected)

The build job just finished:

https://copr.fedorainfracloud.org/coprs/gsauthof/dracut-sshd/build/4459171/

**Comment by atemp** [comment]
Nice, thanks a lot! And thanks for creating this project, its really useful!

> Pre-release builds, against CentOS Stream 9 + EPEL 9, this will be changed once RHEL 9 is available.

i will test if this build works with AlmaLinux 9 x86_64 in the next days and report it, if you are interested

**Comment by gsauthof** [comment]
Yes, I am, how did it go?

**Comment by gsauthof** [comment]
Feel free to add an comment regarding the AlmaLinux 9 status.
