### ISSUE TITLE
NetworkManager Early-Boot Configuration Challenges

### ISSUE THREAD

**Issue by tessus** [gsauthof/dracut-sshd#63]
While dracut-sshd works, it also overrides my network configuration.

Before using `dracut-sshd` my network was setup with NetworkManager and there was one entry in `nmcli con show` for my network adapter (but I am using multiple IPs on that interface).

After installing `dracut-sshd`, my "real" network setup no longer works, because after booting up, the setup in `20-wired.network` is active and my NetworkManager setup is not. There are also 2 entries in `nmcli con show` for my adapter now, but the one that was setup during the initramfs phase is active.

In my opinion the network setup for dracut should only be active until the boot process continues.

This is very puzzling to me, because dracut-sshd should not invalidate my previous network setup.

Is there anything I can do to fix this?

**Comment by tessus** [comment]
Additional info:

```
# nmcli conn show
NAME    UUID                                  TYPE      DEVICE
ens18   a2cff458-59ce-4797-980b-9aecca608e07  ethernet  ens18
virbr0  8167be3f-57f6-4d7a-8a62-1489b43efd62  bridge    virbr0
ens18   8de18d67-66e5-3b9c-8bed-c22e2b832bb6  ethernet  --
```

`a2cff458-59ce-4797-980b-9aecca608e07` is the one that was created by dracut-sshd. The funny thing is that even though the `20-wired.network` file includes a DNS entry, the active network connection is without DNS.

`8de18d67-66e5-3b9c-8bed-c22e2b832bb6` is my originally configured network.

I have found a hacky way to fix this, but I'd rather have a proper solution. 

I am sorry to say, but I find it rather strange that I am the first one who runs into this issue. My network setup is nothing out of the ordinary. On this specific server it's just one interface with one IP address and a properly configured DNS.

**Comment by MathieuIci** [comment]
I also started having a similar issue since upgrading to Fedora 36.

After booting completes, my network adapter has 2 IP addresses assigned to it, the one dracut-sshd acquired via DHCP and a second one NetworkManager also acquired via DHCP.

I would swear that previous to upgrading to Fedora 36 my adapter would only have a single IP address, the one NetworkManager acquired.

Since dracut-sshd has not changed recently, perhaps a change to NetworkManager is causing this issue?  (i.e. no longer flushes previous configuration when starting)

**Comment by champtar** [comment]
here a NM issue that should answer all your questions: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/685

**Comment by tessus** [comment]
Well, the nm issue was closed without a fix. These things are really annoying. I opened a ticket with Redhat once. 10 years later it was closed without a fix. Just brilliant.

Haha, my hack was a slightly bigger script:

```bash
#!/bin/bash

CONN="$1"

if [ -z "$CONN" ]; then
	echo "Error: A NetworkManager device must be specified"
	exit 1
fi

if [ ! -e /etc/NetworkManager/system-connections/$CONN.nmconnection ]; then
	echo "Error: the connection for device [$CONN] does not exist."
	exit 2
fi

if [ "`systemctl is-active NetworkManager`" != "active" ]; then
	echo "Error: NetworkManager is not running."
	exit 3
fi

VALID_UUID=`cat /etc/NetworkManager/system-connections/$CONN.nmconnection |grep uuid |cut -d= -f2`

#echo $VALID_UUID

DEV=`nmcli connection show |grep $VALID_UUID | awk '{print $4}'`

if [ "$DEV" != "$CONN" ]; then
	#echo "Network must be fixed."
	N=`nmcli connection show |grep -v $VALID_UUID |grep $CONN |wc -l`
	if [ "$N" != "1" ]; then
		echo "Error: Something unexpected happened."
		echo "   Either no active connection found or more than one connection active."
		echo "   Manual intervention is necessary."
		exit 13
	fi
	CONN_TO_KILL=`nmcli connection show |grep -v $VALID_UUID |grep $CONN |awk '{print $2}'`

	#echo $CONN_TO_KILL
	nmcli connection down uuid $CONN_TO_KILL
	echo "All good now. Have fun!"
else
	echo "All good. Nothing to fix. Yippie!"
	exit 0
fi
```

```
[Unit]
Description=Fix network, after dracut-sshd creates a network connection which overrides the configured network.
After=network.target NetworkManager.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/sbin/dracut-fix-network.sh INTERFACE

[Install]
WantedBy=multi-user.target
```

**Comment by gsauthof** [comment]
Hm, so it looks like this is a generic limitation of how NetworkManager works and there isn't really something I can change in dracut-sshd?

I mean you would run into similar issues even without activating `dracut-sshd`, i.e. simply by enabling `rd.neednet=1 ip=dhcp` (or similar) for another dracut service that requires network connectivity.

FWIW, I don't use NetworkManager for wired interfaces and prefer to use systemd-networkd instead, where possible, especially for servers.

Even for wireless interfaces NetworkManager IMHO is suboptimal and I hope that it gets replaced by something like iwd, on distributions I use.

Also, Redhat's decision to get rid of networkd in RHEL >= 8 and the attempt to consolidate all network configuration with NetworkManager is a huge mistake, in opinion.
I even prefer to use network-scripts over NetworkManager, on RHEL <= 8 servers.

**Comment by tessus** [comment]
Yep, I think we can close this. But maybe you can create a label called `Info` or something or convert it to a discussion.

I agree with you. I liked the plain network scripts much better, but I had to accept the fact that nm won't go away. Apparently plain text files are a no-no these days, even though the nm also creates text files in the background.

It also doesn't seem that the nm devs are going to fix this, especially since [champter's issue](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/685) what auto-closed without a fix.

It is a trend these days to make simple things that worked for many, many years (without any problems) more complicted. When they break (and it's only a question of when and not if), the geniuses who came up with the new design either ignore the newly introduced bugs or just weasel themselves out of it by selling them as a part of the new design. What a mess.

**Comment by purpleidea** [comment]
> It is a trend these days to make simple things that worked for many, many years (without any problems) more complicted.

No, you're unnecessarily simplifying things. The advantage of the newer tools (NetworkManager, systemd-networkd) are that you can actually have event streams when things change, and that is very useful and for some use-cases, essential. NM did this first, and networkd jumped in afterwards in an attempt to make it simpler.

HTH

**Comment by tessus** [comment]
> have event streams when things change

I don't see this relevant for a server. A server has a static IP, we are not removing and plagging in network cables, using WiFi with x differernt SSID, and we are not adding new IP addresses on a daily basis. And even before nm that was possible without a reboot.
If you are talking overlay networks that's a whole different story and tbh NM is also not so great for those.

**Comment by purpleidea** [comment]
For a very boring, under-manager server you might not need this. My work involves bringing events into modern automation work. If you'd like to see what that can get you, have a look here: https://github.com/purpleidea/mgmt/

**Comment by tessus** [comment]
I like your project. It would be nice to add trace points via OpenTelemetry though.

I have used Chef, SaltStack, and Ansible as a cfg management tool - and all of them had certain challenges (with NetworkManager or not). But I think we are a bit off-topic now...
