### ISSUE TITLE
Rocky Linux 9, Permission denied (publickey)

### ISSUE THREAD

**Issue by Renarde1312** [gsauthof/dracut-sshd#64]
Hi trying to set dracut-sshd to unlock my home server remotely and I get the Permision denied (publickey) error.

I've tried to change the root accound unlocking method following using `sudo usermod -p '*' root` and regenerating the initramfs with `sudo dracut -f -v`

The auth key file is the same as the one I use to unlock my account after unlocking so it should work.

I don't get what I'm doing wrong.

**Comment by gsauthof** [comment]
Are you able to troubleshoot this in an environment where you also have console access such that you can look at possible error messages/missing files in real time, in the early boot environment, i.e. when you are trying to ssh-login into it?

See also the last item of https://github.com/gsauthof/dracut-sshd#faq

**Comment by Renarde1312** [comment]
I reinstalled my OS and it work now.
The only difference is that my keys are in `/root/.ssh/authorized_keys` instead of `/etc/dracut-sshd/authorized_keys`

**Comment by gsauthof** [comment]
Hm, strange. The authorized_keys selection code arguably is kind of regular:

https://github.com/gsauthof/dracut-sshd/blob/f195fa3b541d122de48f67c23cd2b8aa7c05bb45/46sshd/module-setup.sh#L40-L50

Did you have a chance to verify whether the right key ended up into the initramfs archive (e.g. by unpacking it into a temporary directory and inspecting `/some/path/to/tempdir/root/.ssh/authorized_keys`), before reinstalling?

**Comment by Renarde1312** [comment]
I checked and I somehow added ":wq" to my key.... I'm a moron.
Thanks for the help and for maintaining this project.
