### ISSUE TITLE
-sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf-8)

### ISSUE THREAD

**Issue by tessus** [gsauthof/dracut-sshd#76]
I am getting the following message when I log into the dracut sshd:

```
-sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf-8)
```

I am not sure why I get this message all of a sudden. I upgraded my client OS (macOS) from where I start the ssh session, but on the server side I didn't change anything.
However, I didn't change any ssh client side parameters either.

Wouldn't it make sense to remove the `AcceptEnv` directives in `sshd_config`? If the dracut env does not even have the most standard locale (as in the locale mostly used in North America plus mostly on all server Linux boxes), it's useless to accept the env vars in the first place.

What do you think?

**Comment by gsauthof** [comment]
Hm, when I added that sshd_config to dracut-sshd I basically used the Fedora's default sshd_config and stripped it down.


At that time Fedora's version included those AcceptEnv directives and I thought that they might be useful to some.

However, on current up-to-date Fedora systems I can't find any such settings, anymore.
Apparently, Fedora's defaults changed in the meantime.

The current man page specifies:

> The default is **not** to accept **any** environment variables.

https://manpath.be/f39/5/sshd_config#L28 (emphasis mine)

Also, at least on current Fedora, ssh doesn't send any environment variables (besides TERM), by default, anyways:

> The default is **not** to send **any** environment variables.

https://manpath.be/f39/5/ssh_config#L1069 (emphasis mine)

Thus, I think it should be fine for sshd-dracut to remove all those `AcceptEnv` directives.

---

You might also want to check your Mac ssh client regarding recent changes in its `SendEnv` defaults or configuration.

**Comment by gsauthof** [comment]
Some context:

- Fedora 36: [Bug 2002739](https://bugzilla.redhat.com/show_bug.cgi?id=2002739) - Disable locale forwarding in OpenSSH
- RHEL 9: [Bug 2002734](https://bugzilla.redhat.com/show_bug.cgi?id=2002734) - Disable locale forwarding in OpenSSH

**Comment by tessus** [comment]
> You might also want to check your Mac ssh client regarding recent changes in its SendEnv defaults or configuration.

I did check again after I opened this issue. My client config (in my home dir) hasn't changed, but the system-wide client config in `/etc` did have the SendEnv entries. I guess the upgrade wiped my changed system-wide config.

Anyway, I think I will also remove the `AcceptEnv` in the dracut sshd.

I think I can close this. Thanks for your reply.
