### ISSUE TITLE
OpenSSH fails to start on RHEL 8.9

### ISSUE THREAD

**Issue by bdurant** [gsauthof/dracut-sshd#77]
The following is emitted at the console in a continuous loop when using dracut-sshd on RHEL 8.9 (it works fine on RHEL 8.2):

[  OK  ] Stopped OpenSSH server daemon.
         Starting OpenSSH server daemon...
[ 3085.684495] systemd[1]: Failed to start OpenSSH server daemon.
[FAILED] Failed to start OpenSSH server daemon.
See 'systemctl status sshd.service' for details.
[  OK  ] Stopped OpenSSH server daemon.
         Starting OpenSSH server daemon...
[ 3127.934681] systemd[1]: Failed to start OpenSSH server daemon.
[FAILED] Failed to start OpenSSH server daemon.
See 'systemctl status sshd.service' for details.
[  OK  ] Stopped OpenSSH server daemon.
         Starting OpenSSH server daemon...

**Comment by bdurant** [comment]
Any ideas on how to resolve that problem?

**Comment by gsauthof** [comment]
Thank you for the report. I would try to reproduce the issue in a VM and if this is reproducible also take a look at the sshd logs.

See also the last point under: https://github.com/gsauthof/dracut-sshd?tab=readme-ov-file#faq

**Comment by bdurant** [comment]
The issue was pilot error i.e. my problem.
