### ISSUE TITLE
sshd service is stopped shortly after start

### ISSUE THREAD

**Issue by mvforell** [gsauthof/dracut-sshd#78]
I've been using dracut-sshd for quite some time now on my Raspberry Pi 4 to remotely unlock a LUKS volume, and it's been working just fine since I set it up. So first of all, thank you for this project!

However, today I seem to have changed something that caused my setup to not work any more. The only thing that I remember changing was that I added a new key to `/etc/dracut-sshd/authorized_keys`; then I regenerated the initramfs and rebooted. Since then I'm unable to SSH into the machine, and I've been unable to find out why exactly. (I'd be surprised if that was what caused this issue, most likely I forgot about something else I did between the last reboot that worked and this next, failed reboot.)

I hooked the RPi up to a monitor and connected a keyboard so I could access the emergency shell. There, everything seems to be working fine (network etc.), but for some reason the sshd service is automatically stopped ~2 seconds after it successfully started.

This is the output of `journalctl -b | grep -C 5 sshd` from the emergency shell:

<details>
<summary><code>journalctl -b | grep -C 5 sshd</code></summary>
<pre>
May 28 14:52:39 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/systemd-ask-password-console.path
May 28 14:52:39 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/syslog.socket
May 28 14:52:39 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/sysinit.target
May 28 14:52:39 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/sys-kernel-config.mount
May 28 14:52:39 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/swap.target
May 28 14:52:39 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/sshd.service
May 28 14:52:39 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/sockets.target
May 28 14:52:39 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/slices.target
May 28 14:52:39 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/sigpwr.target
May 28 14:52:39 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/shutdown.target
May 28 14:52:39 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/rpcbind.target
--
May 28 14:52:39 rpi4 kernel: usb 2-2: SerialNumber: DD8202211117B
May 28 14:52:39 rpi4 kernel: scsi host0: uas
May 28 14:52:39 rpi4 kernel: scsi 0:0:0:0: Direct-Access     Intenso                   1214 PQ: 0 ANSI: 6
May 28 14:52:39 rpi4 (kmod)[136]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
May 28 14:52:39 rpi4 (kmod)[136]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
May 28 14:52:39 rpi4 (sshd)[138]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
May 28 14:52:39 rpi4 (sshd)[138]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
May 28 14:52:39 rpi4 (sshd)[138]: sshd.service: Referenced but unset environment variable evaluates to an empty string: CRYPTO_POLICY, OPTIONS, SSHD_OPTS
May 28 14:52:39 rpi4 (les-load)[140]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
May 28 14:52:39 rpi4 (les-load)[140]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
May 28 14:52:39 rpi4 (journald)[139]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
May 28 14:52:39 rpi4 (journald)[139]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
May 28 14:52:39 rpi4 (journald)[139]: systemd-journald.service: Enabled MemoryDenyWriteExecute= with PR_SET_MDWE
--
May 28 14:52:39 rpi4 systemd-journald[139]: Journal started
May 28 14:52:39 rpi4 systemd-journald[139]: Runtime Journal (/run/log/journal/40c72fbb5a2d4ef48019b4ef0f563795) is 8.0M, max 75.7M, 67.7M free.
May 28 14:52:39 rpi4 systemd-journald[139]: systemd-journald running as PID 139 for the system.
May 28 14:52:39 rpi4 systemd-modules-load[140]: apply: /etc/modules-load.d/gnutls.conf
May 28 14:52:39 rpi4 systemd-vconsole-setup[142]: Sysfs UTF-8 flag disabled
May 28 14:52:39 rpi4 sshd[138]: Server listening on 0.0.0.0 port 22.
May 28 14:52:39 rpi4 sshd[138]: Server listening on :: port 22.
May 28 14:52:39 rpi4 systemd-vconsole-setup[142]: UTF-8 kbdmode disabled on /dev/tty1
May 28 14:52:39 rpi4 systemd-vconsole-setup[142]: Executing "/usr/bin/loadkeys -q -C /dev/tty1 us"...
May 28 14:52:39 rpi4 systemd-journald[139]: Sent READY=1 notification.
May 28 14:52:39 rpi4 systemd-journald[139]: Sent WATCHDOG=1 notification.
May 28 14:52:39 rpi4 systemd-journald[139]: Successfully sent stream file descriptor to service manager.
--
May 28 14:52:40 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/systemd-ask-password-console.path
May 28 14:52:40 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/syslog.socket
May 28 14:52:40 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/sysinit.target
May 28 14:52:40 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/sys-kernel-config.mount
May 28 14:52:40 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/swap.target
May 28 14:52:40 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/sshd.service
May 28 14:52:40 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/sockets.target
May 28 14:52:40 rpi4 (udev-worker)[292]: event1: /usr/lib/udev/rules.d/60-persistent-input.rules:42 Added SYMLINK 'input/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1:1.1-event'
May 28 14:52:40 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/slices.target
May 28 14:52:40 rpi4 systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/sigpwr.target
May 28 14:52:40 rpi4 (udev-worker)[292]: event1: /usr/lib/udev/rules.d/60-persistent-input.rules:44 Added SYMLINK 'input/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usbv2-0:1.1:1.1-event'
--
May 28 14:52:41 rpi4 systemd[1]: Bus private-bus-connection: changing state AUTHENTICATING → RUNNING
May 28 14:52:41 rpi4 systemctl[376]: Bus n/a: changing state AUTHENTICATING -> RUNNING
May 28 14:52:41 rpi4 systemctl[376]: Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=StartUnit cookie=1 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Got message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=StartUnit  cookie=1 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: initrd-switch-root.target: Trying to enqueue job initrd-switch-root.target/start/isolate
May 28 14:52:41 rpi4 systemd[1]: sshd.service: Installed new job sshd.service/stop as 126
May 28 14:52:41 rpi4 systemd[1]: local-fs-pre.target: Installed new job local-fs-pre.target/stop as 123
May 28 14:52:41 rpi4 systemd[1]: slices.target: Installed new job slices.target/stop as 125
May 28 14:52:41 rpi4 systemd[1]: swap.target: Installed new job swap.target/stop as 145
May 28 14:52:41 rpi4 systemd[1]: timers.target: Installed new job timers.target/stop as 139
May 28 14:52:41 rpi4 systemd[1]: network.target: Installed new job network.target/stop as 128
--
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/network_2etarget interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=57 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/timers_2etarget interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=58 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/swap_2etarget interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=59 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/slices_2etarget interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=60 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/local_2dfs_2dpre_2etarget interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=61 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/sshd_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=62 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/sshd_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=63 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobNew cookie=64 reply_cookie=0 signature=uos error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobNew cookie=65 reply_cookie=0 signature=uos error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobNew cookie=66 reply_cookie=0 signature=uos error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobNew cookie=67 reply_cookie=0 signature=uos error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobNew cookie=68 reply_cookie=0 signature=uos error-name=n/a error-message=n/a
--
May 28 14:52:41 rpi4 systemd[1]: dracut-pre-udev.service: stopping held back, waiting for: systemd-udevd.service
May 28 14:52:41 rpi4 systemd[1]: initrd-switch-root.service: starting held back, waiting for: initrd-switch-root.target
May 28 14:52:41 rpi4 systemd[1]: initrd-udevadm-cleanup-db.service: starting held back, waiting for: systemd-udev-trigger.service
May 28 14:52:41 rpi4 systemd[1]: kmod-static-nodes.service: stopping held back, waiting for: systemd-tmpfiles-setup-dev-early.service
May 28 14:52:41 rpi4 systemd[1]: system.slice: Thawing unit.
May 28 14:52:41 rpi4 systemd[1]: sshd.service: Thawing unit.
May 28 14:52:41 rpi4 sshd[138]: Received signal 15; terminating.
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/sshd_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=153 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/sshd_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=154 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: sshd.service: Changed running -> stop-sigterm
May 28 14:52:41 rpi4 systemd[1]: Stopping OpenSSH server daemon...
May 28 14:52:41 rpi4 systemd[1]: systemd-modules-load.service: stopping held back, waiting for: systemd-sysctl.service
May 28 14:52:41 rpi4 systemd[1]: systemd-network-generator.service: stopping held back, waiting for: network-pre.target
May 28 14:52:41 rpi4 systemd[1]: system.slice: Thawing unit.
May 28 14:52:41 rpi4 systemd[1]: systemd-networkd.service: Thawing unit.
--
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/local_2dfs_2etarget interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=183 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dtmpfiles_2dsetup_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=184 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dtmpfiles_2dsetup_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=185 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dnetworkd_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=186 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dnetworkd_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=187 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/sshd_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=188 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/sshd_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=189 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/dracut_2dinitqueue_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=190 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/dracut_2dinitqueue_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=191 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/timers_2etarget interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=192 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/swap_2etarget interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=193 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/sysinit_2etarget interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=194 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
--
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/initrd_2droot_2ddevice_2etarget interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=204 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/basic_2etarget interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=205 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/initrd_2etarget interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=206 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/job/118 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=207 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/job/126 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=208 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Received SIGCHLD from PID 138 (sshd).
May 28 14:52:41 rpi4 systemd[1]: Child 138 (sshd) died (code=exited, status=0/SUCCESS)
May 28 14:52:41 rpi4 systemd[1]: sshd.service: Child 138 belongs to sshd.service.
May 28 14:52:41 rpi4 systemd[1]: sshd.service: Main process exited, code=exited, status=0/SUCCESS (success)
May 28 14:52:41 rpi4 systemd[1]: sshd.service: Deactivated successfully.
May 28 14:52:41 rpi4 systemd[1]: sshd.service: Service restart not allowed.
May 28 14:52:41 rpi4 systemd[1]: sshd.service: Changed stop-sigterm -> dead
May 28 14:52:41 rpi4 systemd[1]: sshd.service: Job 126 sshd.service/stop finished, result=done
May 28 14:52:41 rpi4 systemd[1]: Stopped OpenSSH server daemon.
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/sshd_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=209 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/sshd_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=210 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobRemoved cookie=211 reply_cookie=0 signature=uoss error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: sshd.service: Consumed 49ms CPU time.
May 28 14:52:41 rpi4 systemd[1]: sshd.service: Releasing resources...
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/sshd_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=212 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/sshd_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=213 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: systemd-networkd.service: Got notification message from PID 324 (STOPPING=1, STATUS=Shutting down...)
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dnetworkd_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=214 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dnetworkd_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=215 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 28 14:52:41 rpi4 systemd[1]: systemd-journald.service: Received EPOLLHUP on stored fd 50 (stored), closing.
May 28 14:52:41 rpi4 systemd[1]: Got message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1/unit/initrd_2dswitch_2droot_2etarget interface=org.freedesktop.DBus.Properties member=Get  cookie=3 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
</pre>
</details>

Some excerpts that seem relevant to me:
1. We can see the service starts as expected:
  ```
May 28 14:52:39 rpi4 sshd[138]: Server listening on 0.0.0.0 port 22.
May 28 14:52:39 rpi4 sshd[138]: Server listening on :: port 22.
  ```
2. But then it is stopped again:
  ```
May 28 14:52:41 rpi4 systemd[1]: initrd-switch-root.target: Trying to enqueue job initrd-switch-root.target/start/isolate
May 28 14:52:41 rpi4 systemd[1]: sshd.service: Installed new job sshd.service/stop as 126
...
May 28 14:52:41 rpi4 systemd[1]: sshd.service: Thawing unit.
May 28 14:52:41 rpi4 sshd[138]: Received signal 15; terminating.
  ```

I'm not super familiar with systemd, so I don't really have a clue what could be causing the service to be stopped.

I'd be very grateful for tips on how to further debug this, or maybe you already have an idea how to fix the issue.

**Comment by mvforell** [comment]
I'm using Arch Linux ARM.

**Comment by gsauthof** [comment]
I'm not familiar with Arch, thus I don't know whether it packages sshd/dracut significantly different than other distributions.

However, another thing to check is the service type of the early sshd.

By default, dracut-sshd expects sshd to support systemd style notification support, cf. the comments in the service file and README:

https://github.com/gsauthof/dracut-sshd/blob/6ee590b8ea94a12a3334bb4d597e51b97397c776/46sshd/sshd.service#L8-L25

https://github.com/gsauthof/dracut-sshd/blob/6ee590b8ea94a12a3334bb4d597e51b97397c776/README.md?plain=1#L92-L99

However, 2 s seems to be a bit short for hitting the default timeout, when an expected notification doesn't arrive.

---

Otherwise it looks like the early boot environment kills your sshd because it proceeds with switching root.

Usually, the switch-root target should be blocked by an encrypted volume that isn't unlocked yet, if it contains a filesystem that is required by later boot.

Thus, perhaps something changed in that corner of your setup.

To investigate it further you can check whether any `root=,,, rd.luks.uuid=...`  kernel parameters and/or crypttab files that are included in your initramfs still make sense.

**Comment by mvforell** [comment]
Thanks for your reply! I'm quite busy at the moment, but I will look into this some more based on your suggestions once I find the time.

**Comment by mvforell** [comment]
Finally found some time for this.

First, #79 doesn't seem to have changed things.

> Otherwise it looks like the early boot environment kills your sshd because it proceeds with switching root.

Pretty sure that's it. I've added the `x-initrd.mount` option to the fstab entry for the decrypted LUKS partition, and now I see
```
A start job is running for /dev/mapper/cryptssd
```
and the initrd SSH server works again.

However, when I run `systemd-tty-ask-password-agent` in the SSH shell, nothing happens; for some reason, systemd doesn't want to unlock the partition. Note that I have `rd.luks.name=$UUID=cryptssd` in the kernel cmdline, not doing that has made `systemd-tty-ask-password-agent` not work in the past, but this time it doesn't seem to help.

`cryptsetup` also isn't available in initrd, so I have no way of unlocking the partition from the SSH shell.

I suppose I could configure dracut to install `cryptsetup` into the initramfs; but I have a feeling that what's causing `systemd-tty-ask-password-agent` not to work is also responsible for me having to suddenly add  `x-initrd.mount` to fstab. Do you have any tips, or should I file an issue with dracut directly?

**Comment by gsauthof** [comment]
Hm, it sounds like systemd-cryptsetup-generator doesn't find the right configuration or setup for generating the  `systemd-cryptsetup@.service` during early boot.

See also: https://www.freedesktop.org/software/systemd/man/latest/systemd-cryptsetup-generator.html

You could try to debug it in the early boot shell in a similar way as described in Example 3: https://www.freedesktop.org/software/systemd/man/latest/systemd.generator.html

---

FWIW, on a F39 I regularly unlock I make the luks encrypted root filesystem known to early boot via kernel parameters and kernel parameters:

```
root=UUID=$rootfs_uuid rd.luks.uuid=$luks_uuid
```

and:

```
cat /etc/crypttab 
luks-$luks_uuid UUID=$luks_uuid none discard
```

The initrd contains the following cryptsetup related files:

```
lsinitrd | grep crypt | grep -v '\.so\|crypto'
crypt
-rw-r--r--   1 root     root          110 Nov 16  2023 etc/crypttab
-rwxr-xr-x   1 root     root         8167 Dec 24  2022 usr/lib/dracut-crypt-lib.sh
-rwxr-xr-x   1 root     root         8087 Dec 24  2022 usr/lib/dracut/hooks/cmdline/30-parse-crypt.sh
-rw-r--r--   1 root     root        28832 Nov 16  2023 usr/lib/modules/6.10.10-100.fc39.x86_64/kernel/drivers/md/dm-crypt.ko.xz
-rwxr-xr-x   1 root     root        41176 Nov 16  2023 usr/lib/systemd/system-generators/systemd-cryptsetup-generator
-rw-r--r--   1 root     root          473 Nov 16  2023 usr/lib/systemd/system/cryptsetup-pre.target
-rw-r--r--   1 root     root          420 Nov 16  2023 usr/lib/systemd/system/cryptsetup.target
lrwxrwxrwx   1 root     root           27 Nov 16  2023 usr/lib/systemd/system/initrd-root-device.target.wants/remote-cryptsetup.target -> ../remote-cryptsetup.target
-rw-r--r--   1 root     root          557 Nov 16  2023 usr/lib/systemd/system/remote-cryptsetup.target
lrwxrwxrwx   1 root     root           20 Nov 16  2023 usr/lib/systemd/system/sysinit.target.wants/cryptsetup.target -> ../cryptsetup.target
-rwxr-xr-x   1 root     root        90912 Nov 16  2023 usr/lib/systemd/systemd-cryptsetup
-rw-r--r--   1 root     root           35 Jul 19  2023 usr/lib/tmpfiles.d/cryptsetup.conf
-rwxr-xr-x   1 root     root          804 Dec 24  2022 usr/sbin/crypt-run-generator
```

---

You can also double-check whether the UUIDs match via something like:

```
tr ' ' '\n' < /proc/cmdline | grep -f <(ls /dev/disk/by-uuid) -F
```

**Comment by mvforell** [comment]
Just updated my Raspberry Pi and the issue seems to be resolved now. Pretty sure it was an issue with dracut, it got updated from 103 to 105, and checking the release notes and related issues I found https://github.com/dracut-ng/dracut-ng/issues/563, which sounds very familiar:
> From what I traced 102 isn't including systemd-cryptsetup-generator thus there is no unit to activate. 101 includes it, and 102 and 103 don't.

Thanks again for your help!
