### ISSUE TITLE
Missing subprocess files (arch linux, just after updating ssh)

### ISSUE THREAD

**Issue by koraa** [gsauthof/dracut-sshd#80]
I had to add the following files to make my dracut config work again:

```
FILES=(
  /usr/lib/ssh/ssh-keysign
  /usr/lib/ssh/ssh-pkcs11-helper
  /usr/lib/ssh/ssh-sk-helper
  /usr/lib/ssh/sftp-server
  /usr/lib/ssh/sshd-session
)
```

This issue started to appear right after a system upgrade involving ssh.

I am using an arch based system, using the following AUR package to install this project:

https://aur.archlinux.org/packages/dracut-sshd-git

I don't know which files need to be added; my sshd complained about missing `sshd-session` at the very least. I just included the entire /usr/lib/ssh/ directory.

I suppose this might be the root cause behind #78 and #79.

Thanks for creating this project!

cheers
karolin

**Comment by koraa** [comment]
Actually, this probably *is* fixed by #79 and might be the root cause of #78

**Comment by ellisonpatterson** [comment]
> Actually, this probably _is_ fixed by #79 and might be the root cause of #78

The PR I made 100% fixes the issue, we ONLY need sshd-session.

The concern is though that they have reported that the devs will split that file up even more so I'm wondering if we should just include ANY file prefixed with sshd* and like you have said, those other files as well.

**Comment by ellisonpatterson** [comment]
For now though, you can just make a file `/etc/dracut.conf.d/openssh.conf` and add ` install_optional_items+=" /usr/lib64/misc/sshd-session "`

Then just rebuild the initramfs and you're good to go!

**Comment by ellisonpatterson** [comment]
@koraa An immediate fix though would be to do this:
Make a file called `/etc/dracut.conf.d/openssh.conf` and put the following contents in it:
`install_optional_items+=" /usr/lib/ssh/sshd-session /usr/lib/ssh/ssh-pkcs11-helper /usr/lib/ssh/ssh-sk-helper /usr/lib/ssh/sftp-server /usr/lib/ssh/sshd-session "`

Then rebuild the initramfs.

That should then at least work no matter what for ARCH.

**Comment by gsauthof** [comment]
Thank you for reporting this!

I wasn't aware of this sshd development!

FWIW, Fedora Rawhide is still at openssh 9.6.p1, currently.

I'll take a look at the linked pull request.
