### ISSUE TITLE
Stopped working on Fedora 40

### ISSUE THREAD

**Issue by gus4rs** [gsauthof/dracut-sshd#83]
Environment
```
OpenSSH_9.6p1, OpenSSL 3.2.1 30 Jan 2024
Fedora release 40 (Forty)
```

Initialization logs:

```
-- Boot 365a3ea653bf4882b521b3831acbace3 --
Aug 19 08:03:33 localhost sshd[242]: WARNING: 'UsePAM no' is not supported in Fedora and may cause several problems.
Aug 19 08:03:33 localhost sshd[242]: Server listening on 0.0.0.0 port 22.
Aug 19 08:03:33 localhost sshd[242]: Server listening on :: port 22.
Aug 19 08:03:33 localhost systemd[1]: Started sshd.service - OpenSSH server daemon.
Aug 19 08:10:12 localhost systemd[1]: Stopping sshd.service - OpenSSH server daemon...
Aug 19 08:10:12 localhost sshd[242]: Received signal 15; terminating.    
Aug 19 08:10:12 localhost systemd[1]: sshd.service: Deactivated successfully.
Aug 19 08:10:12 localhost systemd[1]: Stopped sshd.service - OpenSSH server daemon.
Aug 19 08:10:12 localhost systemd[1]: sshd.service: Consumed 2.111s CPU time, 1.3M memory peak, 0B memory swap peak.
Aug 19 08:18:16 localhost.localdomain systemd[1]: Starting sshd.service - OpenSSH server daemon...
```

The exactly same ```dracut-ssh``` version works fine when on ```Fedora 39``` with  and ```OpenSSH_9.3p1, OpenSSL 3.1.1 ```

**Comment by gus4rs** [comment]
```
commit 4dc958ddb50a2b412f4fa9f0eaf59edb37006ba2 (HEAD -> master, tag: 0.6.7, origin/master, origin/HEAD)
```

**Comment by gus4rs** [comment]
The versions all match, except I am on ```aarch64``` in a Parallels VM

And the other difference is that I am not installing ```dracut-ssh``` using DNF, but checking out the sources from github and copying ```dracut-sshd/46sshd``` to ```/usr/lib/dracut/modules.d```

Where

**Comment by gus4rs** [comment]
Any recommendations on how to debug the problem?

**Comment by gus4rs** [comment]
UPDATE

Enabling emergency shell, and added a few utilities inside the initdram (```nc``` and ```ip```):

Emergency shell:
```
# nc localhost 22
SSH-2.0-OpenSSH_9.6
```

```
# ip a
1: lo <LOOPBACK>
...
```

So the SSHD service is correctly started but it seems the network is down...

**Comment by gsauthof** [comment]
Good find!

And thanks for documenting it here such that other potentially affected users may find it.

**Comment by Cydhra** [comment]
Specifically, I couldn't get it to work with `systemd-networkd`, it only worked with the `network` module. Thanks for that, I was trying to fix that for hours
