### ISSUE TITLE
Fedora builds are broken F40/F41

### ISSUE THREAD

**Issue by wiesl** [gsauthof/dracut-sshd#84]
Hello,

Looks like the Fedora builds are broken:
https://copr.fedorainfracloud.org/coprs/gsauthof/dracut-sshd/packages/
dracut-sshd	0.6.7-1
Last Build Status failed

Transaction failed: Signature verification failed.
PGP check for package "dracut-sshd-0.6.7-1.fc41.noarch" (/var/cache/libdnf5/copr:copr.fedorainfracloud.org:gsauthof:dracut-sshd-4ca0fb62a49dce4f/packages/dracut-sshd-0.6.7-1.fc41.noarch.rpm) from repo "copr:copr.fedorainfracloud.org:gsauthof:dracut-sshd" has failed: Problem occurred when opening the package.

Can you please fix it.

Thnx.

**Comment by gsauthof** [comment]
The last copr only failed partially, i.e. on 1 of 17 targets:
https://copr.fedorainfracloud.org/coprs/gsauthof/dracut-sshd/build/7831017/

(and IIRC it only failed on EPEL9 x86_64 due to a broken build environment in the copr infrastructure, at that time)

Perhaps it's a similar issue as analyzed in #82 ?

**Comment by gsauthof** [comment]
I believe that this issue is resolved.
Feel free to reopen it if you think that your problem isn't related to the linked issue.

**Comment by wiesl** [comment]
No, still open, now with Fedora F41:
Transaction failed: Signature verification failed.
PGP check for package "dracut-sshd-0.6.7-1.fc41.noarch" (/var/cache/libdnf5/copr:copr.fedorainfracloud.org:gsauthof:dracut-sshd-4ca0fb62a49dce4f/packages/dracut-sshd-0.6.7-1.fc41.noarch.rpm) from repo "copr:copr.fedorainfracloud.org:gsauthof:dracut-sshd" has failed: Problem occurred when opening the package.

Any ideas?

**Comment by gsauthof** [comment]
> Any ideas?

Well, you can try the workaround mentioned in the linked issue:

https://github.com/gsauthof/dracut-sshd/issues/82#issuecomment-2272310136

Or some other way where you remove the dracut-sshd copr repository and add it back again.

Copr upstream hasn't fixed the issue, yet.

**Comment by wiesl** [comment]
Thnx, workaround worked :-)
