### ISSUE TITLE
sshd only working on reboot

### ISSUE THREAD

**Issue by grasegger** [gsauthof/dracut-sshd#85]
Hi, 

I am very puzzled by this: I configured dracut-sshd (fedora40), but I have the following consistent behaviour:

- cold boot => no sshd available before entering the password, after that the "normal" sshd is started
- reboot => dracut-sshd works as expected, without a problem

The mac address of the nic is configured (in the router) to always get the same ip using dhcp.
I use the same network config for initrd and the system, systemd-networkd. 

I am a bit stumped on how to handle this. Any pointers?

**Comment by gsauthof** [comment]
FWIW, I can't reproduce this with the latest Fedora 40 cloud images.

See also https://github.com/gsauthof/dracut-sshd?tab=readme-ov-file#testing and the `test/` subdirectory of this repository for details on that setup, i.e. that end-to-end test simply copies the stock `example/90-networkd.conf` to `/etc/dracut.conf.d/90-networkd.conf` and doesn't apply any other changes to `/etc/dracut.conf.d/`.
