### ISSUE TITLE
No password prompt, stuck at start job running for /dev/mapper/luks...

### ISSUE THREAD

**Issue by nlambert** [gsauthof/dracut-sshd#86]
I've been using dracut-sshd for a little while without issue, until recently after an upgrade.

I'm now running into the following problem:
1. I can ssh into the machine
2. I can see the welcome message
3. I can press the up arrow key and I can run `systemd-tty-ask-password-agent` BUT...
4. **... But no password prompt appears**
5. I go over to the concerned machine to find that the boot process is stuck at "a start job running for /dev/mapper/luks...". If I remember correctly I could also type my password directly on the aforementioned machine running dracut-sshd.

My system is fully updated.

I also reinstalled and made sure to pull a fresh copy of the git repo. I'm running an arch based system. We have a helper that we can run: `yay -S dracut-sshd`.

Just in case, I manually check that everthing is done as per the readme.

I used a live boot usb to make sure I can unlock my drive `cryptsetup open /dev/nvme0n1p2` which works fine with a passphrase.

I'm at a loss at this point. Hopefully someone can help out.

![Screenshot_20241022_151006](https://github.com/user-attachments/assets/ac321846-7fef-466e-846b-fd9edf9cbbc5)

**Comment by nlambert** [comment]
You know what... this is not at all related to dracut-sshd

sorry for the noise.

**Comment by nlambert** [comment]
for posterity: `add_dracutmodules+=" crypt dm `

in any file under `/etc/dracut.conf.d/` or create your own file

rebuild your initframfs `dracut -f` on endeavour os you should run `reinstall_kernels` make sure your /boot drive is mounted

**Comment by gsauthof** [comment]
FWIW, on Fedora those modules `crypt dm`  are included, by default.

**Comment by dhardtke** [comment]
Had the same problem after installing kernel updates on my fedora 40 server.
For me it was prompting me for a password but it did not matter what I provided: It did not unlock. The suggested fix from @nlambert worked, though.

**Comment by gsauthof** [comment]
@dhardtke interesting, is your dracut configured for `hostonly` operation?

**Comment by dhardtke** [comment]
I don't see it in any config file under /etc/dracut.conf.d or inside /etc/dracut.conf so I guess not.
